set-option global tabstop 4
set-option global indentwidth 4
set-option global BOM none

set-option global autoinfo command|onkey

set-option global ui_options ncurses_assistant=none

set-option global scrolloff 2,5

set-option global makecmd 'make --jobs=8'
set-option global grepcmd 'ag --filename --column --ignore tags'

# stop c and d from yanking
map global normal d \"_d
map global normal c \"_c

# tab/backtab to cycle through completions
hook global InsertCompletionShow .* %{
    map window insert <tab> <c-n>
    map window insert <backtab> <c-p>
}
hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <backtab> <c-p>
}

# use w to select current word
map global normal w <a-i>w
map global normal <a-w> <a-i>W
map global normal W ":exec *\%s<ret><ret>"
map global normal <a-W> ""

# append registers by default (old behavior)
map global normal <a-z> "<a-z>a"
map global normal <a-Z> "<a-Z>a"

set-face Whitespace rgb:404040,default
set-face LineNumbersWrapped rgb:606060,default+i

hook global WinCreate .* %{
    add-highlighter number_lines -hlcursor -separator ' '
    add-highlighter show_matching
    add-highlighter dynregex '%reg{/}' 0:default,rgb:373b41
    add-highlighter show_whitespaces
    add-highlighter wrap -word
}

define-command reload-all -docstring "Reload all open buffers" %{
    eval -buffer * "edit!"
}

define-command kakrc -docstring "Open kakrc" %{
    edit %sh{ printf %s ${XDG_CONFIG_HOME}/kak/kakrc }
}

# add heterogenous selection (could work better)
define-command search-add %{
    eval -save-regs / %{
        exec -save-regs '' Z
        prompt 'search add:' %{ exec -save-regs '' ':reg / ' %val{text} <ret>zN }
    }
}

map -docstring "surround" global user s :surround<ret>
map -docstring "surround (repeated)" global user S :surround-repeat<ret>
map -docstring "expand" global user e :expand<ret>
map -docstring "expand (repeated)" global user E :expand-repeat<ret>
map -docstring "itersel" global user r :interactive-itersel<ret>
map -docstring "copy selections down" global user v :copy-selections-down<ret>
map -docstring "copy selections up" global user <a-v> :copy-selections-up<ret>
map -docstring "copy selections vertically" global user V :copy-selections-vertically<ret>
map -docstring "clip-paste after" global user p '<a-!>xsel --output --clipboard<ret>'
map -docstring "clip-paste before" global user P '!xsel --output --clipboard<ret>'
map -docstring "clip-paste replace" global user R '|xsel --output --clipboard<ret>'
map -docstring "clip-yank" global user y '<a-|>xsel --input --clipboard<ret>'
map -docstring "search add" global user / :search-add<ret>
map -docstring "lf"  global user d :lf<ret>

source ~/.config/kak/friendly-session-names.kak
source ~/.config/kak/interactive-itersel.kak
source ~/.config/kak/lf.kak
source ~/.config/kak/buffers-info.kak
source ~/.config/kak/find.kak
source ~/.config/kak/surround.kak
source ~/.config/kak/expand.kak
source ~/.config/kak/sudo-write.kak
source ~/.config/kak/vertical-selection.kak
try %{ source ~/prog/forks/kakoune/rc/extra/gdb.kak }
try %{ source ~/.config/kak/dayjob.kak }
