set-option global tabstop 4
set-option global indentwidth 4
set-option global BOM none

set-option global autoinfo command|onkey

set-option global ui_options ncurses_assistant=none

set-option global scrolloff 2,5

set-option global makecmd 'make --jobs=8'
set-option global grepcmd 'ag --filename --column --ignore tags'

# c and d don't yank
map global normal d \"_d
map global normal c \"_c

map global goto n <esc>:grep-next<ret>
map global goto p <esc>:grep-prev<ret>

# tab/backtab to cycle through completions
hook global InsertCompletionShow .* %{
    map window insert <tab> <c-n>
    map window insert <backtab> <c-p>
}
hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <backtab> <c-p>
}

#interaction with system clipboard through user mappings
map global user p '<a-!>xsel --output --clipboard<ret>'
map global user P '!xsel --output --clipboard<ret>'
define-command yank-to-sys-clip %{ exec -draft '<a-|>xsel --input --clipboard<ret>' }
map global user y ':yank-to-sys-clip<ret>'

set-face Whitespace rgb:505050,default
set-face LineNumbersWrapped rgb:606060,default+i

hook global WinCreate .* %{
    add-highlighter number_lines -relative -hlcursor -separator ' '
    add-highlighter show_matching
    add-highlighter show_whitespaces
    add-highlighter dynregex '%reg{/}' 0:default,rgb:373b41
    add-highlighter wrap -word
}

define-command kakrc -docstring "Open kakrc" %{
    edit %sh{ printf %s ${XDG_CONFIG_HOME}/kak/kakrc }
}

# add heterogenous selection (could work better)
define-command search_add %{
    eval -save-regs / %{
        exec -save-regs '' Z
        prompt \
            -on-abort %{ exec z } \
            'search add:' %{ exec -save-regs '' ':reg / ' %val{text} <ret>zN }
    }
}
map global user / :search_add<ret>

# Buffers (by danr 2017, public domain)
map global normal <a-,> :bp<ret>:bufinfo<ret>
map global normal <a-.> :bn<ret>:bufinfo<ret>
map global normal <a-minus> ga:bufinfo<ret>
map global normal <a-d> :db<ret>:bufinfo<ret>
map global normal <a-q> :db!<ret>:bufinfo<ret>
def bufinfo %{
    %sh{
        printf "info -- %%:"
        printf "$kak_buflist" | tr ':' '\n' |
        while read buf; do
            if [ "$buf" = "$kak_bufname" ]; then
                printf "> %s <\n" "$buf"
            else
                printf "  %s  \n" "$buf"
            fi
        done
        printf :\\n
    }
}

source ~/.config/kak/interactive_itersel.kak
source ~/.config/kak/lf.kak
try %{ source ~/prog/forks/kakoune/rc/extra/gdb.kak }
try %{ source ~/.config/kak/dayjob.kak }
