#! /bin/sh

bspc config border_width          3
bspc config window_gap            12
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true
bspc config click_to_focus        true

bspc monitor -d I II III IV V
